language: java
dist: trusty
jdk:
  - openjdk8
  - openjdk11
  - openjdk-ea
  - oraclejdk8
  - oraclejdk11
sudo: false
after_success:
  - bash <(curl -s https://codecov.io/bash)
matrix:
  allow_failures:
    - jdk: openjdk-ea
