name: Tests

on: [ push ]

jobs:
  jdk:
    name: JDK ${{ matrix.java_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java_version: [ '8', '9', '10', '11', '12', '13', '14', '15', '16', '17' ]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java_version }}
      - run: git submodule update --init
      - run: ./gradlew --no-daemon jvmTest
